### ISSUE TITLE
Add tests for `@yamada-ui/scroll-area`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#358]
related: #74

### Description

Currently, no tests in `@yamada-ui/scroll-area`. In the future, I feel the need for testing when operating `@yamada-ui/scroll-area`.

### Problem Statement/Justification

Testing is essential to ensure quality when operating a package.

**Comment by You-saku** [comment]
@hirotomoyamada 
Hi I'm You-saku. 
I'm not good at frontend. However, I would like to try this issue. Is it possible?

(I sent you a message in English, but I'm Japanese)

**Comment by hirotomoyamada** [comment]
@You-saku 

Hi, thanks for the comment.

Yes, please.

**Comment by hirotomoyamada** [comment]
@You-saku 

Hi, Thanks for the working on this issue!

What is the status of this issue?

Tomorrow, We will return this issue assignment to initial state.

If you are working on this issue and would like to extend it, please contact us.

**Comment by You-saku** [comment]
@hirotomoyamada 

HI!

>What is the status of this issue?

It's **Doing**. But It's too difficult for current me... 🙇‍♂️ 
I was able to create a test file, but I'm not sure what to test. [progress](https://github.com/You-saku/yamada-ui/blob/test/scroll-area/packages/components/scroll-area/tests/scroll-area.test.tsx)


>If you are working on this issue and would like to extend it, please contact us.

Thanks. But I'm willing to have the assignment reset because with my current skills, it's going to take me a long time to contribute.

I'm willing to contribute, so I'll continue to work on reading existing code and improving my TypeScript and CSS skills 👍

**Comment by hirotomoyamada** [comment]
@You-saku 

Hi! Understood.

Take your time to improve your skills, and we look forward to your future contributions.

Best of luck with your studies!
