### ISSUE TITLE
Add tests for `@yamada-ui/transitions`

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-ui#370]
related: #74

### Description

Currently, no tests in `@yamada-ui/transitions`. In the future, I feel the need for testing when operating `@yamada-ui/transitions`.

### Problem Statement/Justification

Testing is essential to ensure quality when operating a package.

**Comment by 000000armor** [comment]
Hi @hirotomoyamada ! Can I work on this one?

**Comment by hirotomoyamada** [comment]
@000000armor 

Hi, thanks for the comment!

Yes, please.

Assign it to you. Good luck!

**Comment by 000000armor** [comment]
@hirotomoyamada 
I decided to make a separate PR for `Collapse` tests because the file kind of big. Also want to make sure I am on the same page with repo's code style. Please review it and let me know what do you think. I think  that I will put other tests in main PR (feat/transition-tests)
https://github.com/000000armor/yamada-ui/pull/1

**Comment by hirotomoyamada** [comment]
@000000armor 

Hi, thanks for the contributing.

That's a good idea. I agree with you.

I saw the PR. The code style is generally correct.  "Don's worry, I'm wearing pants!"

Create a file for each component and submit a PR once you have written tests for all components.

**Comment by 000000armor** [comment]
@hirotomoyamada I created a PR, also noticed couple things:
- .coverage folder not added to `.env` file
- there is no command to run tests in watch mode
